//go:build go1.22

// Package boundary provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package boundary

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// ClientRejection The body a request rejected before any upstream call carries back, distinct to its cause and renderable by the frontend.
type ClientRejection struct {
	// Cause Why the request was rejected. An open string; the cause set is not fixed here.
	Cause string `json:"cause"`

	// Message Plain-language text the frontend renders.
	Message string `json:"message"`
}

// UpstreamFailure The body a module's failed data request carries back, distinct to its cause so an operator can tell a source being down from a key being wrong.
type UpstreamFailure struct {
	// Cause What kind of failure this was. An open string; the cause set is not fixed here.
	Cause string `json:"cause"`

	// Message Plain-language text the module renders as its error state.
	Message string `json:"message"`

	// Module The module whose request failed, so the failure is contained to its own place.
	Module string `json:"module"`
}

// WeatherCurrent The weather at the location at present.
type WeatherCurrent struct {
	// ApparentTemp How warm it feels, in degrees Fahrenheit.
	ApparentTemp float64 `json:"apparentTemp"`

	// Humidity Relative humidity, as a percentage.
	Humidity float64 `json:"humidity"`

	// IsDay Whether it is daylight at the location.
	IsDay bool `json:"isDay"`

	// Temp Air temperature, in degrees Fahrenheit.
	Temp float64 `json:"temp"`

	// WeatherCode What the sky is doing, as a WMO 4677 present-weather code. An open standard rather than a supplier's vocabulary, so what draws it maps the code to its own icon.
	WeatherCode int `json:"weatherCode"`

	// WindSpeed Wind speed, in miles per hour.
	WindSpeed float64 `json:"windSpeed"`
}

// WeatherDay The weather expected at the location for one day to come.
type WeatherDay struct {
	// Max The warmest the day is expected to get, in degrees Fahrenheit.
	Max float64 `json:"max"`

	// Min The coldest the day is expected to get, in degrees Fahrenheit.
	Min float64 `json:"min"`

	// PrecipProbability The chance of precipitation, as a percentage.
	PrecipProbability float64 `json:"precipProbability"`

	// Time The day this entry is for, as an ISO 8601 timestamp at that day's start carrying the location's own UTC offset — `2026-08-31T00:00:00-04:00`.
	Time string `json:"time"`

	// WeatherCode What the sky is expected to be doing, as a WMO 4677 present-weather code.
	WeatherCode int `json:"weatherCode"`
}

// WeatherHour The weather expected at the location for one hour to come.
type WeatherHour struct {
	// IsDay Whether it is daylight at the location for this hour.
	IsDay bool `json:"isDay"`

	// PrecipProbability The chance of precipitation, as a percentage.
	PrecipProbability float64 `json:"precipProbability"`

	// Temp Air temperature expected, in degrees Fahrenheit.
	Temp float64 `json:"temp"`

	// Time The hour this entry is for, as an ISO 8601 timestamp carrying the location's own UTC offset — `2026-08-31T14:00:00-04:00` — so the hour is unambiguous wherever it is read.
	Time string `json:"time"`

	// WeatherCode What the sky is expected to be doing, as a WMO 4677 present-weather code.
	WeatherCode int `json:"weatherCode"`
}

// WeatherPayload The weather module's payload: what the weather is doing at one location now, and what it is expected to do over the hours and the days next to come. Every temperature here is in degrees Fahrenheit and every wind speed in miles per hour — the units are the schema's, so no value on the wire carries one and no consumer converts.
type WeatherPayload struct {
	// Current The weather at the location at present.
	Current WeatherCurrent `json:"current"`

	// Daily The days next to come, nearest first. How many is the shaping library's.
	Daily []WeatherDay `json:"daily"`

	// Hourly The hours next to come, nearest first. How many is the shaping library's.
	Hourly []WeatherHour `json:"hourly"`
}

// WeatherRequest The point a request names. It is the whole of what this route reads of a request, so the two names below are defined here and nowhere else on either side.
type WeatherRequest struct {
	// Lat Latitude of the point, in decimal degrees north of the equator.
	Lat float64 `json:"lat"`

	// Lon Longitude of the point, in decimal degrees east of the prime meridian.
	Lon float64 `json:"lon"`
}

// PostApiWeatherJSONRequestBody defines body for PostApiWeather for application/json ContentType.
type PostApiWeatherJSONRequestBody = WeatherRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostApiWeatherWithBody Report the weather at a point on the earth's surface.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
	PostApiWeatherWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiWeather Report the weather at a point on the earth's surface.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
	PostApiWeather(ctx context.Context, body PostApiWeatherJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealthz Report that the backend process is serving.
	//
	// Corresponds with GET /healthz (the `GetHealthz` operationId).
	GetHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostApiWeatherWithBody Report the weather at a point on the earth's surface.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
func (c *Client) PostApiWeatherWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiWeatherRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostApiWeather Report the weather at a point on the earth's surface.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
func (c *Client) PostApiWeather(ctx context.Context, body PostApiWeatherJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiWeatherRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHealthz Report that the backend process is serving.
//
// Corresponds with GET /healthz (the `GetHealthz` operationId).
func (c *Client) GetHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiWeatherRequest calls the generic PostApiWeather builder with application/json body
func NewPostApiWeatherRequest(server string, body PostApiWeatherJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiWeatherRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiWeatherRequestWithBody constructs an http.Request for the PostApiWeather method, with any body, and a specified content type
func NewPostApiWeatherRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/weather")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthzRequest constructs an http.Request for the GetHealthz method
func NewGetHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostApiWeatherWithBodyWithResponse Report the weather at a point on the earth's surface.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
	PostApiWeatherWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiWeatherResponse, error)

	// PostApiWeatherWithResponse Report the weather at a point on the earth's surface.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
	PostApiWeatherWithResponse(ctx context.Context, body PostApiWeatherJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiWeatherResponse, error)

	// GetHealthzWithResponse Report that the backend process is serving.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `GetHealthz` operationId).
	GetHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthzResponse, error)
}

type PostApiWeatherResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *WeatherPayload
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ClientRejection
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *ClientRejection
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *UpstreamFailure
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *UpstreamFailure
	// JSON504 the response for an HTTP 504 `application/json` response
	JSON504 *UpstreamFailure
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostApiWeatherResponse) GetJSON200() *WeatherPayload {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostApiWeatherResponse) GetJSON400() *ClientRejection {
	return r.JSON400
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r PostApiWeatherResponse) GetJSON429() *ClientRejection {
	return r.JSON429
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r PostApiWeatherResponse) GetJSON502() *UpstreamFailure {
	return r.JSON502
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r PostApiWeatherResponse) GetJSON503() *UpstreamFailure {
	return r.JSON503
}

// GetJSON504 returns the response for an HTTP 504 `application/json` response
func (r PostApiWeatherResponse) GetJSON504() *UpstreamFailure {
	return r.JSON504
}

// GetBody returns the raw response body bytes
func (r PostApiWeatherResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostApiWeatherResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiWeatherResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiWeatherResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r GetHealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostApiWeatherWithBodyWithResponse Report the weather at a point on the earth's surface.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
func (c *ClientWithResponses) PostApiWeatherWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiWeatherResponse, error) {
	rsp, err := c.PostApiWeatherWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiWeatherResponse(rsp)
}

// PostApiWeatherWithResponse Report the weather at a point on the earth's surface.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/weather (the `PostApiWeather` operationId).
func (c *ClientWithResponses) PostApiWeatherWithResponse(ctx context.Context, body PostApiWeatherJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiWeatherResponse, error) {
	rsp, err := c.PostApiWeather(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiWeatherResponse(rsp)
}

// GetHealthzWithResponse Report that the backend process is serving.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `GetHealthz` operationId).
func (c *ClientWithResponses) GetHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthzResponse, error) {
	rsp, err := c.GetHealthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthzResponse(rsp)
}

// ParsePostApiWeatherResponse parses an HTTP response from a PostApiWeatherWithResponse call
func ParsePostApiWeatherResponse(rsp *http.Response) (*PostApiWeatherResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiWeatherResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WeatherPayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ClientRejection
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ClientRejection
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest UpstreamFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest UpstreamFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest UpstreamFailure
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseGetHealthzResponse parses an HTTP response from a GetHealthzWithResponse call
func ParseGetHealthzResponse(rsp *http.Response) (*GetHealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostApiWeather Report the weather at a point on the earth's surface.
	// (POST /api/weather)
	PostApiWeather(w http.ResponseWriter, r *http.Request)
	// GetHealthz Report that the backend process is serving.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiWeather operation middleware
func (siw *ServerInterfaceWrapper) PostApiWeather(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiWeather(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/weather", wrapper.PostApiWeather)

	return m
}
