// Package boundary provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package boundary

// ClientRejection The body a request rejected before any upstream call carries back, distinct to its cause and renderable by the frontend.
type ClientRejection struct {
	// Cause Why the request was rejected. An open string; the cause set is not fixed here.
	Cause string `json:"cause"`

	// Message Plain-language text the frontend renders.
	Message string `json:"message"`
}

// UpstreamFailure The body a module's failed data request carries back, distinct to its cause so an operator can tell a source being down from a key being wrong.
type UpstreamFailure struct {
	// Cause What kind of failure this was. An open string; the cause set is not fixed here.
	Cause string `json:"cause"`

	// Message Plain-language text the module renders as its error state.
	Message string `json:"message"`

	// Module The module whose request failed, so the failure is contained to its own place.
	Module string `json:"module"`
}
