settings:
  digits: 3
  itemformat: yaml
  parent: SYS
  prefix: SRS
  sep: ''
attributes:
  defaults:
    status: proposed
    verification-method: ''
    rationale: ''
  reviewed:
  - rationale
  - verification-method
