settings:
  digits: 3
  itemformat: yaml
  parent: SRS
  prefix: TST
  sep: ''
attributes:
  defaults:
    status: proposed
    verification-method: ''
    verification-justification: ''
    rationale: ''
  reviewed:
  - rationale
  - verification-method
  - verification-justification
