/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The region of the display this module is laid out into, from the fixed roster.
 */
export type Region =
  | "top_bar"
  | "top_left"
  | "top_center"
  | "top_right"
  | "upper_third"
  | "middle_center"
  | "lower_third"
  | "bottom_left"
  | "bottom_center"
  | "bottom_right"
  | "bottom_bar";
/**
 * The name of the module to render, as the page registers it.
 */
export type Module = string;
/**
 * What this placement asks of the module it names. The keys on offer are the named module's own, declared in that module's section below, and a module with no section there is not judged by another module's keys; two placements of the same module are configured apart, each from its own entry.
 */
export type ModuleOptions = ClockOptions | WeatherOptions | {};
/**
 * Whether the hour is presented in twenty-four-hour form. False presents it in twelve-hour form, carrying the indicator that tells the two halves of the day apart.
 */
export type TwentyFourHour = boolean;
/**
 * Whether the seconds of the current time are shown beside the rest of it.
 */
export type ShowSeconds = boolean;
/**
 * Whether the current date is shown beside the time.
 */
export type ShowDate = boolean;
/**
 * Latitude of the point, in decimal degrees north of the equator.
 */
export type Latitude = number;
/**
 * Longitude of the point, in decimal degrees east of the prime meridian.
 */
export type Longitude = number;
/**
 * Seconds the Next Hours graph shows each series — temperature, then precipitation — before switching between them. Floored at two seconds, below which the switch would strobe.
 */
export type SeriesSwitchSeconds = number;
/**
 * Every module this deployment displays, each with the region it is laid out into. A region may carry several modules, and a region no entry names holds nothing.
 */
export type Modules = ModulePlacement[];
/**
 * Depth of the masked band every laid-out region keeps clear of, on all four edges, as a percentage of the display's height — the same unit the type and spacing scales are stated in. Omit it where the display presents its own edge; nothing is assumed in its absence.
 */
export type EdgeBand = number;

export interface WiseKioskDisplayConfiguration {
  modules: Modules;
  edge_band?: EdgeBand;
}
export interface ModulePlacement {
  region: Region;
  module: Module;
  options?: ModuleOptions;
}
/**
 * The clock module's section: what a placement of the clock may ask of it. Every key is omissible, and a clock configured with none of them takes the defaults below.
 */
export interface ClockOptions {
  twenty_four_hour?: TwentyFourHour;
  show_seconds?: ShowSeconds;
  show_date?: ShowDate;
}
/**
 * The weather module's section: what a placement of the weather module asks of it. Its one required key carries no default — the module reports on a point on the earth's surface, and there is no point that would do in the absence of one the placement names. Every other key is omissible, and a placement configured with none of them takes the defaults below.
 */
export interface WeatherOptions {
  location: WeatherLocation;
  series_switch_seconds?: SeriesSwitchSeconds;
}
/**
 * The point the weather is reported at. Two placements of the module report on two points, each from its own entry.
 */
export interface WeatherLocation {
  lat: Latitude;
  lon: Longitude;
}
