/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The region of the display this module is laid out into, from the fixed roster.
 */
export type Region =
  | "top_bar"
  | "top_left"
  | "top_center"
  | "top_right"
  | "upper_third"
  | "middle_center"
  | "lower_third"
  | "bottom_left"
  | "bottom_center"
  | "bottom_right"
  | "bottom_bar"
  | "fullscreen_above"
  | "fullscreen_below";
/**
 * The name of the module to render, as the page registers it.
 */
export type Module = string;
/**
 * Every module this deployment displays, each with the region it is laid out into. A region may carry several modules, and a region no entry names holds nothing.
 */
export type Modules = ModulePlacement[];
/**
 * Depth of the masked band every laid-out region keeps clear of, on all four edges, as a percentage of the display's height — the same unit the type and spacing scales are stated in. Omit it where the display presents its own edge; nothing is assumed in its absence.
 */
export type EdgeBand = number;

export interface WiseKioskDisplayConfiguration {
  modules: Modules;
  edge_band?: EdgeBand;
}
export interface ModulePlacement {
  region: Region;
  module: Module;
}
