/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The region of the display this module is laid out into, from the fixed roster.
 */
export type Region =
  | "top_bar"
  | "top_left"
  | "top_center"
  | "top_right"
  | "upper_third"
  | "middle_center"
  | "lower_third"
  | "bottom_left"
  | "bottom_center"
  | "bottom_right"
  | "bottom_bar";
/**
 * The name of the module to render, as the page registers it.
 */
export type Module = string;
/**
 * What this placement asks of the module it names. The keys on offer are the named module's own, declared in that module's section below, and a module with no section there is not judged by another module's keys; two placements of the same module are configured apart, each from its own entry.
 */
export type ModuleOptions = ClockOptions | {};
/**
 * Whether the hour is presented in twenty-four-hour form. False presents it in twelve-hour form, carrying the indicator that tells the two halves of the day apart.
 */
export type TwentyFourHour = boolean;
/**
 * Whether the seconds of the current time are shown beside the rest of it.
 */
export type ShowSeconds = boolean;
/**
 * Whether the current date is shown beside the time.
 */
export type ShowDate = boolean;
/**
 * Every module this deployment displays, each with the region it is laid out into. A region may carry several modules, and a region no entry names holds nothing.
 */
export type Modules = ModulePlacement[];
/**
 * Depth of the masked band every laid-out region keeps clear of, on all four edges, as a percentage of the display's height — the same unit the type and spacing scales are stated in. Omit it where the display presents its own edge; nothing is assumed in its absence.
 */
export type EdgeBand = number;

export interface WiseKioskDisplayConfiguration {
  modules: Modules;
  edge_band?: EdgeBand;
}
export interface ModulePlacement {
  region: Region;
  module: Module;
  options?: ModuleOptions;
}
/**
 * The clock module's section: what a placement of the clock may ask of it. Every key is omissible, and a clock configured with none of them takes the defaults below.
 */
export interface ClockOptions {
  twenty_four_hour?: TwentyFourHour;
  show_seconds?: ShowSeconds;
  show_date?: ShowDate;
}
