#!/usr/bin/env python3
"""Normalizes every generated `.dot` artifact under docs/architecture/generated/ and renders it to
`.svg`, with the system Graphviz `dot` binary.

Run as a step of `just arch-export`, between `likec4 gen dot` and `scripts/splice-arch-diagrams.py`:
`likec4 gen dot` emits the graph structure — including the element descriptions and icons Mermaid
codegen drops — as DOT text with no computed layout (`ADR 0003 rev 4`); the graph's own
`layout=dot` attribute is Graphviz's, so `dot -Tsvg` is what actually lays it out. Browser-free: no
chromium, only the system `dot` binary CI installs alongside the LikeC4 toolchain.

Two non-deterministic byte sources are stripped, confirmed empirically (#115): re-rendering the
`.dot` LikeC4 emits from an unchanged model, in a fresh process, yields a different `likec4_id` value
per relationship each time — an internal id `likec4 export json` was already known not to hold
stable across machines (ADR 0003 rev 4), which turns out to leak into `gen dot` too. Stripped from
the `.dot` file itself, which `check-arch` diffs byte-for-byte same as the `.svg`. Separately, `dot
-Tsvg` embeds its own version in a header comment (`<!-- Generated by graphviz version X (Y) -->`),
which would otherwise move the gate on a Graphviz version alone. Both stripped so the committed
artifacts' only variable is the model.

What this has been run against, in both directions: cases/check-arch.md
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "docs" / "architecture" / "generated"

VERSION_COMMENT = re.compile(rb"<!-- Generated by graphviz version.*?-->\n?", re.DOTALL)
# LikeC4's own internal element/relationship id, an attribute Graphviz never interprets and nothing
# downstream reads; not deterministic across processes, so it fails the byte-diff gate on no model
# change at all if left in.
# Two DOT shapes carry this attribute: an inline `[likec4_id=x, ...]` list (comma-terminated, no
# space around `=`) on most views, and `likec4_id = "x";` statements (space, semicolon-terminated)
# on the deployment view's multi-line node and edge blocks.
LIKEC4_ID_LINE = re.compile(
    rb'^[ \t]*likec4_id\s*=\s*(?:"[^"]*"|[^,;\]\s]+)[,;][ \t]*\n', re.MULTILINE
)


def fail(msg):
    print(f"render-arch-svg: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    dot_files = sorted(GENERATED.glob("*.dot"))
    if not dot_files:
        fail("no .dot artifact under docs/architecture/generated/ — did `likec4 gen dot` run first?")

    for dot_file in dot_files:
        dot_text = LIKEC4_ID_LINE.sub(b"", dot_file.read_bytes())
        dot_file.write_bytes(dot_text)

        result = subprocess.run(["dot", "-Tsvg", str(dot_file)], capture_output=True)
        if result.returncode != 0:
            fail(f"{dot_file.name}: `dot -Tsvg` failed: {result.stderr.decode(errors='replace')}")
        svg = VERSION_COMMENT.sub(b"", result.stdout)
        dot_file.with_suffix(".svg").write_bytes(svg)

    print(f"Rendered {len(dot_files)} .dot artifact(s) to .svg via the system Graphviz `dot` binary.")


if __name__ == "__main__":
    main()
