#!/usr/bin/env python3
"""Renders every generated `.dot` artifact under docs/architecture/generated/ to `.svg`, with the
system Graphviz `dot` binary.

Run as a step of `just arch-export`, between `likec4 gen dot` and `scripts/splice-arch-diagrams.py`:
`likec4 gen dot` emits the graph structure — including the element descriptions and icons Mermaid
codegen drops — as DOT text with no computed layout (`ADR 0003 rev 4`); the graph's own
`layout=dot` attribute is Graphviz's, so `dot -Tsvg` is what actually lays it out. Browser-free: no
chromium, only the system `dot` binary CI installs alongside the LikeC4 toolchain.

`dot -Tsvg` embeds its own version in a header comment (`<!-- Generated by graphviz version X (Y)
-->`), which would otherwise move `check-arch`'s byte-diff gate on a Graphviz version alone, with no
model change. Stripped so the committed artifact's only variable is the model, confirmed empirically:
re-running this against an unchanged model twice yields byte-identical `.svg` output.

What this has been run against, in both directions: cases/check-arch.md
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "docs" / "architecture" / "generated"

VERSION_COMMENT = re.compile(rb"<!-- Generated by graphviz version.*?-->\n?", re.DOTALL)


def fail(msg):
    print(f"render-arch-svg: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    dot_files = sorted(GENERATED.glob("*.dot"))
    if not dot_files:
        fail("no .dot artifact under docs/architecture/generated/ — did `likec4 gen dot` run first?")

    for dot_file in dot_files:
        result = subprocess.run(["dot", "-Tsvg", str(dot_file)], capture_output=True)
        if result.returncode != 0:
            fail(f"{dot_file.name}: `dot -Tsvg` failed: {result.stderr.decode(errors='replace')}")
        svg = VERSION_COMMENT.sub(b"", result.stdout)
        dot_file.with_suffix(".svg").write_bytes(svg)

    print(f"Rendered {len(dot_files)} .dot artifact(s) to .svg via the system Graphviz `dot` binary.")


if __name__ == "__main__":
    main()
