/**
 * Generated by orval 🍺
 * Do not edit manually.
 * WiseKiosk boundary contract
 * OpenAPI spec version: 0.1.0
 */
/**
 * The body a module's failed data request carries back, distinct to its cause so an operator can tell a source being down from a key being wrong.
 */
export interface UpstreamFailure {
  /** The module whose request failed, so the failure is contained to its own place. */
  module: string;
  /** What kind of failure this was. An open string; the cause set is not fixed here. */
  cause: string;
  /** Plain-language text the module renders as its error state. */
  message: string;
}

/**
 * The body a request rejected before any upstream call carries back, distinct to its cause and renderable by the frontend.
 */
export interface ClientRejection {
  /** Why the request was rejected. An open string; the cause set is not fixed here. */
  cause: string;
  /** Plain-language text the frontend renders. */
  message: string;
}

export type getHealthzResponse200 = {
  data: void;
  status: 200;
};

export type getHealthzResponseSuccess = getHealthzResponse200 & {
  headers: Headers;
};
export type getHealthzResponse = getHealthzResponseSuccess;

export const getGetHealthzUrl = () => {
  return `/healthz`;
};

/**
 * @summary Report that the backend process is serving.
 */
export const getHealthz = async (
  options?: RequestInit,
): Promise<getHealthzResponse> => {
  const res = await fetch(getGetHealthzUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthzResponse["data"] = body ? JSON.parse(body) : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getHealthzResponse;
};
