/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The body a module's failed data request carries back, distinct to its cause so an operator can tell a source being down from a key being wrong. */
        UpstreamFailure: {
            /** @description The module whose request failed, so the failure is contained to its own place. */
            module: string;
            /** @description What kind of failure this was. An open string; the cause set is not fixed here. */
            cause: string;
            /** @description Plain-language text the module renders as its error state. */
            message: string;
        };
        /** @description The body a request rejected before any upstream call carries back, distinct to its cause and renderable by the frontend. */
        ClientRejection: {
            /** @description Why the request was rejected. An open string; the cause set is not fixed here. */
            cause: string;
            /** @description Plain-language text the frontend renders. */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
